# pyup.io config file 
# see https://pyup.io/docs/configuration/ for all available options

# configure updates globally, default is all
update: all # allowed [all, insecure, False]

# update schedule, default is not set
# the bot will visit the repo once and bundle all updates in a single PR for the given
# day/week/month
schedule: "every week" # allowed ["every day", "every week", "every two weeks", "every month"]
